[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
PROMPT_TOOLKIT_COLOR_DEPTH="DEPTH_24_BIT"
TERM = "xterm-256color"

[font]
size = 13
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }


[scrolling]
history = 10000

[mouse]
hide_when_typing = true

[cursor]
vi_mode_style = "Block"

[[keyboard.bindings]]
action = "SearchForward"
key = "R"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
command.program = "sh"
command.args = ["-c", "alacritty msg creat-window --command ranger \"$PWD\""]

[[hints.enabled]]
binding = { key = "X", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
post_processing = true
mouse.enabled = true
regex = """
(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https:??|http://|news:|file:|
git://|ssh://|ftp://)[^\u0000-\u001F-\u009F<>\"\\s{-}\\^()`]+"""

[window]
decorations = "Buttonless"
padding = { x = 10, y = 1 }
dynamic_padding = true
opacity = 0.7

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.primary]
foreground = "#ebdbb2"

[colors.cursor]
cursor = "#1fe9cd"
text = "#fbdfdf"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.selection]
background = "#665c54"
text = "CellForeground"

[colors.search.matches]
background = "#fabd2f"
foreground = "#282828"

[colors.search.focused_match]
background = "#fe8019"
foreground = "#282828"

[colors.hints.start]
background = "#fabd2f"
foreground = "#282828"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.footer_bar]
background = "#282828"
foreground = "#ebdbb2"

[colors.hints.end]
background = "#282828"
foreground = "#fabd2f"
